input: docs
output: _build
requirements: requirements.txt
target: gh-pages
formats: [ html ]
images:
  latex: btdi/latex
theme: https://github.com/nobodywasishere/sphinx_symbiflow_theme/archive/refs/tags/test.tar.gz
